name: Daily Contribution

on:
  schedule:
    - cron: '12 12 * * *'
  workflow_dispatch:

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set Git Identity
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Update Activity Log
        run: |
          echo "Last contribution: $(date -u +"%Y-%m-%d %H:%M:%S")" >> activity_log.md

      - name: Commit and Push Changes
        run: |
          git add activity_log.md
          git commit -m "Update activity log with timestamp"
          git push origin main
